# Generated by Django 4.1.5 on 2023-01-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0002_alter_answer_answer_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="answer_text",
            new_name="data",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="question_text",
            new_name="data",
        ),
    ]
